# Site settings
title: SV DÃ©esse
email: info@svdeesse.com
author: Taras Kalapun
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://svdeesse.com" # the base hostname & protocol for your site

google_analytics: UA-2087894-2

# permalink: /posts/:title/
relative_permalinks: false

markdown: redcarpet
redcarpet:
  extensions: ["tables", "autolink"]

highlighter: pygments

# gems:
  # - jekyll-redirect-from #https://help.github.com/articles/redirects-on-github-pages
  # - jekyll-mentions

social:
  email: mailto:info@svdeesse.com
  rss: http://svdeesse.com/feed.xml


prose:
  siteurl: "http://svdeesse.com"
  ignore:
    - /_layouts
    - /_includes
    - /_sass
    - /css
    - /fonts
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: true
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "categories"
        field:
          element: "text"
          label: "categories"
      - name: "tags"
        field:
          element: "text"
          label: "tags"
